# Image registry should be same as created in digitalocean_container_registry (infrastructure/main.tf)
apiVersion: skaffold/v2beta25
kind: Config
profiles:
  - name: production
    build:
      artifacts:
        - image: ghcr.io/karanpratapsingh/hypertrade/proxy
          context: ./services/proxy
        - image: ghcr.io/karanpratapsingh/hypertrade/nats
          context: ./services/nats
        - image: ghcr.io/karanpratapsingh/hypertrade/web
          context: ./services/web
          docker:
            target: production
        - image: ghcr.io/karanpratapsingh/hypertrade/exchange
          context: ./services/exchange
          docker:
            target: production
        - image: ghcr.io/karanpratapsingh/hypertrade/notification
          context: ./services/notification
          docker:
            target: production
        - image: ghcr.io/karanpratapsingh/hypertrade/strategy
          context: ./services/strategy
  - name: development
    build:
      artifacts:
        - image: ghcr.io/karanpratapsingh/hypertrade/proxy
          context: ./services/proxy
        - image: ghcr.io/karanpratapsingh/hypertrade/nats
          context: ./services/nats
        - image: ghcr.io/karanpratapsingh/hypertrade/web
          context: ./services/web
          docker:
            target: development
          sync:
            manual:
              - src: "src/**/*.ts*"
                dest: .
        - image: ghcr.io/karanpratapsingh/hypertrade/exchange
          context: ./services/exchange
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: ghcr.io/karanpratapsingh/hypertrade/notification
          context: ./services/notification
          docker:
            target: development
          sync:
            manual:
              - src: "**/*.go"
                dest: .
        - image: ghcr.io/karanpratapsingh/hypertrade/strategy
          context: ./services/strategy
deploy:
  helm:
    releases:
      - name: app
        namespace: hypertrade
        createNamespace: true
        chartPath: infrastructure/k8s
        valuesFiles:
          - infrastructure/k8s/values.yaml
          - infrastructure/k8s/env.yaml
        artifactOverrides:
          images.proxy: ghcr.io/karanpratapsingh/hypertrade/proxy
          images.nats: ghcr.io/karanpratapsingh/hypertrade/nats
          images.exchange: ghcr.io/karanpratapsingh/hypertrade/exchange
          images.notification: ghcr.io/karanpratapsingh/hypertrade/notification
          images.strategy: ghcr.io/karanpratapsingh/hypertrade/strategy
          images.web: ghcr.io/karanpratapsingh/hypertrade/web
portForward:
  - resourceName: proxy
    resourceType: service
    namespace: hypertrade
    port: 8080
    localPort: 8080
  - resourceName: db
    resourceType: service
    namespace: hypertrade
    port: 5432
    localPort: 5432
