name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_SECRETS: ${{ secrets.APP_SECRETS }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure secrets
        run: echo "${{ env.APP_SECRETS }}" | base64 --decode > infrastructure/k8s/env.yaml

      - name: Install skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

      - name: Install helm
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh

      - name: Log in to Github Container Registry
        run: echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Prepare
        run: scripts/prepare.sh production

      - name: Build
        run: make build
